# Mental Wellness Model Configuration

# Model Configuration
model:
  type: "random_forest"  # Options: "random_forest", "logistic_regression"
  test_size: 0.2
  random_state: 42

# Data Configuration
data:
  sample_size: 1000
  target_columns:
    - "depression_risk"
    - "anxiety_risk"
  
  feature_columns:
    - "age"
    - "sleep_hours"
    - "exercise_minutes"
    - "work_stress_level"
    - "mood_rating"
    - "energy_level"
    - "avg_heart_rate"
    - "resting_heart_rate"

# Feature Engineering Configuration
features:
  scaling: true
  create_interactions: true
  age_groups: [25, 35, 50, 65]

# Risk Assessment Thresholds
risk_thresholds:
  low: 0.3
  moderate: 0.6
  high: 0.8

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Cloud Deployment Configuration
cloud:
  # GCS Configuration for Render deployment
  gcs:
    bucket_name: "mental_wellness_data_lake"
    # Credentials loaded from environment variables:
    # Required environment variables for Render:
    # - GOOGLE_CREDENTIALS_JSON (preferred) or individual fields:
    # - GCS_PROJECT_ID
    # - GCS_PRIVATE_KEY  
    # - GCS_CLIENT_EMAIL
    # - GCS_PRIVATE_KEY_ID
  
  # Render-specific settings
  render:
    environment: "production"
    # Port will be set by Render automatically via PORT environment variable